/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsSettingsRouteImport } from './routes/records/settings'
import { Route as RecordsPublishedRouteImport } from './routes/records/published'
import { Route as RecordsPendingRouteImport } from './routes/records/pending'
import { Route as RecordsMessagesRouteImport } from './routes/records/messages'
import { Route as RecordsLoginRouteImport } from './routes/records/login'
import { Route as RecordsDashboardRouteImport } from './routes/records/dashboard'
import { Route as RecordsActivityRouteImport } from './routes/records/activity'
import { Route as ClientSubmitRouteImport } from './routes/client/submit'
import { Route as ClientSettingsRouteImport } from './routes/client/settings'
import { Route as ClientMessagesRouteImport } from './routes/client/messages'
import { Route as ClientLoginRouteImport } from './routes/client/login'
import { Route as ClientFormsRouteImport } from './routes/client/forms'
import { Route as ClientFeedbackRouteImport } from './routes/client/feedback'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as AdminSubmitRequestRouteImport } from './routes/admin/submit-request'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminMyFormsRouteImport } from './routes/admin/my-forms'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFormsRouteImport } from './routes/admin/forms'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as ClientRequestsIndexRouteImport } from './routes/client/requests/index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests/index'
import { Route as AdminMyRequestsIndexRouteImport } from './routes/admin/my-requests/index'
import { Route as AdminAssignedIndexRouteImport } from './routes/admin/assigned/index'
import { Route as RecordsFormsFormIdRouteImport } from './routes/records/forms/$formId'
import { Route as ClientRequestsTicketIdRouteImport } from './routes/client/requests/$ticketId'
import { Route as AdminRequestsTicketIdRouteImport } from './routes/admin/requests/$ticketId'
import { Route as AdminRbacUsersRouteImport } from './routes/admin/rbac/users'
import { Route as AdminRbacRolesRouteImport } from './routes/admin/rbac/roles'
import { Route as AdminRbacPermissionsRouteImport } from './routes/admin/rbac/permissions'
import { Route as AdminMyRequestsTicketIdRouteImport } from './routes/admin/my-requests/$ticketId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsSettingsRoute = RecordsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsPublishedRoute = RecordsPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsPendingRoute = RecordsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsMessagesRoute = RecordsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsLoginRoute = RecordsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsDashboardRoute = RecordsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsActivityRoute = RecordsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => RecordsRoute,
} as any)
const ClientSubmitRoute = ClientSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFormsRoute = ClientFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFeedbackRoute = ClientFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSubmitRequestRoute = AdminSubmitRequestRouteImport.update({
  id: '/submit-request',
  path: '/submit-request',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyFormsRoute = AdminMyFormsRouteImport.update({
  id: '/my-forms',
  path: '/my-forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const ClientRequestsIndexRoute = ClientRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyRequestsIndexRoute = AdminMyRequestsIndexRouteImport.update({
  id: '/my-requests/',
  path: '/my-requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignedIndexRoute = AdminAssignedIndexRouteImport.update({
  id: '/assigned/',
  path: '/assigned/',
  getParentRoute: () => AdminRoute,
} as any)
const RecordsFormsFormIdRoute = RecordsFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => RecordsRoute,
} as any)
const ClientRequestsTicketIdRoute = ClientRequestsTicketIdRouteImport.update({
  id: '/requests/$ticketId',
  path: '/requests/$ticketId',
  getParentRoute: () => ClientRoute,
} as any)
const AdminRequestsTicketIdRoute = AdminRequestsTicketIdRouteImport.update({
  id: '/requests/$ticketId',
  path: '/requests/$ticketId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacUsersRoute = AdminRbacUsersRouteImport.update({
  id: '/rbac/users',
  path: '/rbac/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRolesRoute = AdminRbacRolesRouteImport.update({
  id: '/rbac/roles',
  path: '/rbac/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacPermissionsRoute = AdminRbacPermissionsRouteImport.update({
  id: '/rbac/permissions',
  path: '/rbac/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyRequestsTicketIdRoute = AdminMyRequestsTicketIdRouteImport.update({
  id: '/my-requests/$ticketId',
  path: '/my-requests/$ticketId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/records': typeof RecordsRouteWithChildren
  '/user': typeof UserRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/my-forms': typeof AdminMyFormsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submit-request': typeof AdminSubmitRequestRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/feedback': typeof ClientFeedbackRoute
  '/client/forms': typeof ClientFormsRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/submit': typeof ClientSubmitRoute
  '/records/activity': typeof RecordsActivityRoute
  '/records/dashboard': typeof RecordsDashboardRoute
  '/records/login': typeof RecordsLoginRoute
  '/records/messages': typeof RecordsMessagesRoute
  '/records/pending': typeof RecordsPendingRoute
  '/records/published': typeof RecordsPublishedRoute
  '/records/settings': typeof RecordsSettingsRoute
  '/admin/my-requests/$ticketId': typeof AdminMyRequestsTicketIdRoute
  '/admin/rbac/permissions': typeof AdminRbacPermissionsRoute
  '/admin/rbac/roles': typeof AdminRbacRolesRoute
  '/admin/rbac/users': typeof AdminRbacUsersRoute
  '/admin/requests/$ticketId': typeof AdminRequestsTicketIdRoute
  '/client/requests/$ticketId': typeof ClientRequestsTicketIdRoute
  '/records/forms/$formId': typeof RecordsFormsFormIdRoute
  '/admin/assigned/': typeof AdminAssignedIndexRoute
  '/admin/my-requests/': typeof AdminMyRequestsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/client/requests/': typeof ClientRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/records': typeof RecordsRouteWithChildren
  '/user': typeof UserRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/my-forms': typeof AdminMyFormsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submit-request': typeof AdminSubmitRequestRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/feedback': typeof ClientFeedbackRoute
  '/client/forms': typeof ClientFormsRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/submit': typeof ClientSubmitRoute
  '/records/activity': typeof RecordsActivityRoute
  '/records/dashboard': typeof RecordsDashboardRoute
  '/records/login': typeof RecordsLoginRoute
  '/records/messages': typeof RecordsMessagesRoute
  '/records/pending': typeof RecordsPendingRoute
  '/records/published': typeof RecordsPublishedRoute
  '/records/settings': typeof RecordsSettingsRoute
  '/admin/my-requests/$ticketId': typeof AdminMyRequestsTicketIdRoute
  '/admin/rbac/permissions': typeof AdminRbacPermissionsRoute
  '/admin/rbac/roles': typeof AdminRbacRolesRoute
  '/admin/rbac/users': typeof AdminRbacUsersRoute
  '/admin/requests/$ticketId': typeof AdminRequestsTicketIdRoute
  '/client/requests/$ticketId': typeof ClientRequestsTicketIdRoute
  '/records/forms/$formId': typeof RecordsFormsFormIdRoute
  '/admin/assigned': typeof AdminAssignedIndexRoute
  '/admin/my-requests': typeof AdminMyRequestsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/client/requests': typeof ClientRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/records': typeof RecordsRouteWithChildren
  '/user': typeof UserRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/my-forms': typeof AdminMyFormsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submit-request': typeof AdminSubmitRequestRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/feedback': typeof ClientFeedbackRoute
  '/client/forms': typeof ClientFormsRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/submit': typeof ClientSubmitRoute
  '/records/activity': typeof RecordsActivityRoute
  '/records/dashboard': typeof RecordsDashboardRoute
  '/records/login': typeof RecordsLoginRoute
  '/records/messages': typeof RecordsMessagesRoute
  '/records/pending': typeof RecordsPendingRoute
  '/records/published': typeof RecordsPublishedRoute
  '/records/settings': typeof RecordsSettingsRoute
  '/admin/my-requests/$ticketId': typeof AdminMyRequestsTicketIdRoute
  '/admin/rbac/permissions': typeof AdminRbacPermissionsRoute
  '/admin/rbac/roles': typeof AdminRbacRolesRoute
  '/admin/rbac/users': typeof AdminRbacUsersRoute
  '/admin/requests/$ticketId': typeof AdminRequestsTicketIdRoute
  '/client/requests/$ticketId': typeof ClientRequestsTicketIdRoute
  '/records/forms/$formId': typeof RecordsFormsFormIdRoute
  '/admin/assigned/': typeof AdminAssignedIndexRoute
  '/admin/my-requests/': typeof AdminMyRequestsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/client/requests/': typeof ClientRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/records'
    | '/user'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/my-forms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submit-request'
    | '/client/dashboard'
    | '/client/feedback'
    | '/client/forms'
    | '/client/login'
    | '/client/messages'
    | '/client/settings'
    | '/client/submit'
    | '/records/activity'
    | '/records/dashboard'
    | '/records/login'
    | '/records/messages'
    | '/records/pending'
    | '/records/published'
    | '/records/settings'
    | '/admin/my-requests/$ticketId'
    | '/admin/rbac/permissions'
    | '/admin/rbac/roles'
    | '/admin/rbac/users'
    | '/admin/requests/$ticketId'
    | '/client/requests/$ticketId'
    | '/records/forms/$formId'
    | '/admin/assigned/'
    | '/admin/my-requests/'
    | '/admin/requests/'
    | '/client/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/records'
    | '/user'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/my-forms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submit-request'
    | '/client/dashboard'
    | '/client/feedback'
    | '/client/forms'
    | '/client/login'
    | '/client/messages'
    | '/client/settings'
    | '/client/submit'
    | '/records/activity'
    | '/records/dashboard'
    | '/records/login'
    | '/records/messages'
    | '/records/pending'
    | '/records/published'
    | '/records/settings'
    | '/admin/my-requests/$ticketId'
    | '/admin/rbac/permissions'
    | '/admin/rbac/roles'
    | '/admin/rbac/users'
    | '/admin/requests/$ticketId'
    | '/client/requests/$ticketId'
    | '/records/forms/$formId'
    | '/admin/assigned'
    | '/admin/my-requests'
    | '/admin/requests'
    | '/client/requests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/records'
    | '/user'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/my-forms'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/submit-request'
    | '/client/dashboard'
    | '/client/feedback'
    | '/client/forms'
    | '/client/login'
    | '/client/messages'
    | '/client/settings'
    | '/client/submit'
    | '/records/activity'
    | '/records/dashboard'
    | '/records/login'
    | '/records/messages'
    | '/records/pending'
    | '/records/published'
    | '/records/settings'
    | '/admin/my-requests/$ticketId'
    | '/admin/rbac/permissions'
    | '/admin/rbac/roles'
    | '/admin/rbac/users'
    | '/admin/requests/$ticketId'
    | '/client/requests/$ticketId'
    | '/records/forms/$formId'
    | '/admin/assigned/'
    | '/admin/my-requests/'
    | '/admin/requests/'
    | '/client/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/settings': {
      id: '/records/settings'
      path: '/settings'
      fullPath: '/records/settings'
      preLoaderRoute: typeof RecordsSettingsRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/published': {
      id: '/records/published'
      path: '/published'
      fullPath: '/records/published'
      preLoaderRoute: typeof RecordsPublishedRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/pending': {
      id: '/records/pending'
      path: '/pending'
      fullPath: '/records/pending'
      preLoaderRoute: typeof RecordsPendingRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/messages': {
      id: '/records/messages'
      path: '/messages'
      fullPath: '/records/messages'
      preLoaderRoute: typeof RecordsMessagesRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/login': {
      id: '/records/login'
      path: '/login'
      fullPath: '/records/login'
      preLoaderRoute: typeof RecordsLoginRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/dashboard': {
      id: '/records/dashboard'
      path: '/dashboard'
      fullPath: '/records/dashboard'
      preLoaderRoute: typeof RecordsDashboardRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/activity': {
      id: '/records/activity'
      path: '/activity'
      fullPath: '/records/activity'
      preLoaderRoute: typeof RecordsActivityRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/client/submit': {
      id: '/client/submit'
      path: '/submit'
      fullPath: '/client/submit'
      preLoaderRoute: typeof ClientSubmitRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/forms': {
      id: '/client/forms'
      path: '/forms'
      fullPath: '/client/forms'
      preLoaderRoute: typeof ClientFormsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/feedback': {
      id: '/client/feedback'
      path: '/feedback'
      fullPath: '/client/feedback'
      preLoaderRoute: typeof ClientFeedbackRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/submit-request': {
      id: '/admin/submit-request'
      path: '/submit-request'
      fullPath: '/admin/submit-request'
      preLoaderRoute: typeof AdminSubmitRequestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-forms': {
      id: '/admin/my-forms'
      path: '/my-forms'
      fullPath: '/admin/my-forms'
      preLoaderRoute: typeof AdminMyFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/requests/': {
      id: '/client/requests/'
      path: '/requests'
      fullPath: '/client/requests/'
      preLoaderRoute: typeof ClientRequestsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-requests/': {
      id: '/admin/my-requests/'
      path: '/my-requests'
      fullPath: '/admin/my-requests/'
      preLoaderRoute: typeof AdminMyRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assigned/': {
      id: '/admin/assigned/'
      path: '/assigned'
      fullPath: '/admin/assigned/'
      preLoaderRoute: typeof AdminAssignedIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/records/forms/$formId': {
      id: '/records/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/records/forms/$formId'
      preLoaderRoute: typeof RecordsFormsFormIdRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/client/requests/$ticketId': {
      id: '/client/requests/$ticketId'
      path: '/requests/$ticketId'
      fullPath: '/client/requests/$ticketId'
      preLoaderRoute: typeof ClientRequestsTicketIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/requests/$ticketId': {
      id: '/admin/requests/$ticketId'
      path: '/requests/$ticketId'
      fullPath: '/admin/requests/$ticketId'
      preLoaderRoute: typeof AdminRequestsTicketIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac/users': {
      id: '/admin/rbac/users'
      path: '/rbac/users'
      fullPath: '/admin/rbac/users'
      preLoaderRoute: typeof AdminRbacUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac/roles': {
      id: '/admin/rbac/roles'
      path: '/rbac/roles'
      fullPath: '/admin/rbac/roles'
      preLoaderRoute: typeof AdminRbacRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac/permissions': {
      id: '/admin/rbac/permissions'
      path: '/rbac/permissions'
      fullPath: '/admin/rbac/permissions'
      preLoaderRoute: typeof AdminRbacPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-requests/$ticketId': {
      id: '/admin/my-requests/$ticketId'
      path: '/my-requests/$ticketId'
      fullPath: '/admin/my-requests/$ticketId'
      preLoaderRoute: typeof AdminMyRequestsTicketIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminMyFormsRoute: typeof AdminMyFormsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmitRequestRoute: typeof AdminSubmitRequestRoute
  AdminMyRequestsTicketIdRoute: typeof AdminMyRequestsTicketIdRoute
  AdminRbacPermissionsRoute: typeof AdminRbacPermissionsRoute
  AdminRbacRolesRoute: typeof AdminRbacRolesRoute
  AdminRbacUsersRoute: typeof AdminRbacUsersRoute
  AdminRequestsTicketIdRoute: typeof AdminRequestsTicketIdRoute
  AdminAssignedIndexRoute: typeof AdminAssignedIndexRoute
  AdminMyRequestsIndexRoute: typeof AdminMyRequestsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminMyFormsRoute: AdminMyFormsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmitRequestRoute: AdminSubmitRequestRoute,
  AdminMyRequestsTicketIdRoute: AdminMyRequestsTicketIdRoute,
  AdminRbacPermissionsRoute: AdminRbacPermissionsRoute,
  AdminRbacRolesRoute: AdminRbacRolesRoute,
  AdminRbacUsersRoute: AdminRbacUsersRoute,
  AdminRequestsTicketIdRoute: AdminRequestsTicketIdRoute,
  AdminAssignedIndexRoute: AdminAssignedIndexRoute,
  AdminMyRequestsIndexRoute: AdminMyRequestsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientFeedbackRoute: typeof ClientFeedbackRoute
  ClientFormsRoute: typeof ClientFormsRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientSubmitRoute: typeof ClientSubmitRoute
  ClientRequestsTicketIdRoute: typeof ClientRequestsTicketIdRoute
  ClientRequestsIndexRoute: typeof ClientRequestsIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientFeedbackRoute: ClientFeedbackRoute,
  ClientFormsRoute: ClientFormsRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientSubmitRoute: ClientSubmitRoute,
  ClientRequestsTicketIdRoute: ClientRequestsTicketIdRoute,
  ClientRequestsIndexRoute: ClientRequestsIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface RecordsRouteChildren {
  RecordsActivityRoute: typeof RecordsActivityRoute
  RecordsDashboardRoute: typeof RecordsDashboardRoute
  RecordsLoginRoute: typeof RecordsLoginRoute
  RecordsMessagesRoute: typeof RecordsMessagesRoute
  RecordsPendingRoute: typeof RecordsPendingRoute
  RecordsPublishedRoute: typeof RecordsPublishedRoute
  RecordsSettingsRoute: typeof RecordsSettingsRoute
  RecordsFormsFormIdRoute: typeof RecordsFormsFormIdRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsActivityRoute: RecordsActivityRoute,
  RecordsDashboardRoute: RecordsDashboardRoute,
  RecordsLoginRoute: RecordsLoginRoute,
  RecordsMessagesRoute: RecordsMessagesRoute,
  RecordsPendingRoute: RecordsPendingRoute,
  RecordsPublishedRoute: RecordsPublishedRoute,
  RecordsSettingsRoute: RecordsSettingsRoute,
  RecordsFormsFormIdRoute: RecordsFormsFormIdRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  RecordsRoute: RecordsRouteWithChildren,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
